config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create]

  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy' # Ends (destroys) the session

  root 'welcome#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  def index
      @albums = Album.all
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Add save handlers for formatting data
  before_create :create_remember_token
  before_save :normalize_fields

  # Validates name:
  validates :name,
    presence: true,
    length: { maximum: 50}

  # Validates email:
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false},
    format: { with: /[^@]+@[^@]/ }

  # Validates password:
  validates :password,
    length: { minimum: 8}

  # Secure password features
  has_secure_password

  # create new rember token for the user
  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end
  def self.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

private
  
  # Create a new session token for the user
  def create_remember_token
    remember_token = User.hash(User.new_remember_token)
  end

# Normalize fields for consistency:
  def normalize_fields
    self.email.downcase!
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :set_album, only: [:show, :edit, :update, :delete]

  def index
    @albums = Album.all
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to @album, notice: "Album was successfully created."
    else
      render :new
    end
  end

  def show
  end

  def edit
    # @album = Album.find(album_params)
  end

  def update
    if @album.update(album_params)
      redirect_to @album, notice: "Album was successfully updated."
    else
      render :edit
  end
end

def delete
  @album.destroy
end

private

def set_album
  @album = Album.find(params[:id])
end


def album_params
  params.require(:album).permit(:title, :artist, :year)
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :require_signin
end

app/controllers/concerns/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    render text: "What up?"
  end
end

app/controllers/sessions_controller.rb
# require 'pry'

class SessionsController < ApplicationController
  skip_before_action :require_signin, only: [:new, :create]

  def new
  end

  def create
    # Find user by their email
    # binding.pry
    user = User.find_by(email: params[:session][:email].downcase)

    # Test if the user was found AND authenticates
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      redirect_back_or(root_path)
    else
      flash[:error] = "Invalid email/password"
      redirect_to new_session_path
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  ski[_before_action :require_signin, only: [:new, :create]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      sign_in @user # Sings in a newly signed up user
      redirect_to @user
    else
      render :new # Re-renders the form because of failure to add new user
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def users_params
    params.require(:user).permit( # This is a hash, the given symbol is the key, the user input is the value
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :require_signin, only: [:index]

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user?(user)
    current_user == user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  # Location management methods
  def store_location
    if request.get?
      session[:return_to] = request.url
    end
  end

  # Redirect the user back to where they were before they logged in
  def redirect_back_or(default)
    reditect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  # Security checkpoint:
  def require_signin
    if !signed_in?
      store_location
      flash[:notice] = "Please sign in"
      redirect_to signin_url
    end
  end

end

app/views/albums/edit.html.erb
<%= form_for @album do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :artist %>
  <%= f.text_field :artist %>

  <%= f.label :year %>
  <%= f.text_field :year %>

  <%= f.submit %>

<% end %>

app/views/albums/index.html.erb
<h1>Listing Albums</h1>

<ul class = "albums">
  <% if @albums.empty? %>
  <li>No albums available</li>
  <% else %>
  <% flash.each do |name, msg| -%>
       <%= content_tag :div, msg, class: name %>
     <% end -%>
  <% @albums.each do |album| %>
    <li class="album"><%= link_to album.title, album_path(album) %></li>
  <ul>
    <li class="artist"><%= album.artist %></li>
    <li class="year"><%= album.year %></li>
    <li><%= link_to 'Delete', album_path(album), method: :delete, data: { confirm: 'Are you sure?' } %><li>
  </ul>

  <% end %>
   <% end %>
</ul>

app/views/albums/new.html.erb
<%= form_for @album do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :artist %>
  <%= f.text_field :artist %>

  <%= f.label :year %>
  <%= f.text_field :year %>

  <%= f.submit %>

<% end %>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>

<p>by <%= @album.artist %>, released in <%= @album.year %>.</p>

app/views/common/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :p, msg, class: name %>
<% end %>

app/views/common/_signout.html.erb
<% if signed_in? %>
  <%= form_for :session, url: signout_path, method: 'delete' do |f| %>
    Signed in as <%= link_to current_user.name, current_user %>
    <%= f.submit 'Sign Out', id: 'signout' %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tunr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'common/signout' %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<% if @user.errors.any? %>
<b>Errors:<b>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
      <% end %>
    </ul>
    <%end %>

<%= form_for @user do |f| %>
   <%= f.label :name %>
   <%= f.text_field :name %>

   <%= f.label :email %>
   <%= f.text_field :email %>

   <%= f.label :password %>
   <%= f.password_field :password %>

   <%= f.label :password_confirmation, 'Confirm Password' %>
   <%= f.password_field :password_confirmation %>

   <%= f.submit 'Submit', id: 'submit' %>
 <% end %>

app/views/welcome/index.html.erb
<h1>Yo, sup?</h1>
<img src="http://www.memebots.com/wp-content/uploads/2010/08/yobot-yo-sup-4501.jpg"/>

<br></br>
<%= link_to 'Sign Up', signup_path %>
<%= link_to 'Sign In', signin_path %>